"""OBJ mesh exporter."""

from threedllm.exporters.base import Exporter3D
from threedllm.generators.base import MeshResult


class OBJExporter(Exporter3D):
    """Exports meshes in OBJ format."""

    def get_file_extension(self) -> str:
        """Get the file extension."""
        return ".obj"

    def export(self, result: MeshResult, path: str) -> None:
        """Export mesh as OBJ file."""
        with open(path, "w", encoding="utf-8") as f:
            # Write header
            f.write("# OBJ file generated by ThreeDLLM\n")
            if result.prompt:
                f.write(f"# Prompt: {result.prompt}\n")

            # Write vertices
            for x, y, z in result.vertices:
                f.write(f"v {x:.6f} {y:.6f} {z:.6f}\n")

            # Write faces if available
            if result.faces:
                for face in result.faces:
                    # OBJ uses 1-based indexing
                    f.write(f"f {face[0] + 1} {face[1] + 1} {face[2] + 1}\n")
            elif len(result.vertices) >= 3:
                # Generate simple triangulation if no faces provided
                # This is a basic approach - for production, use proper triangulation
                for i in range(0, len(result.vertices) - 2, 3):
                    f.write(f"f {i + 1} {i + 2} {i + 3}\n")
