"""STL mesh exporter."""

import struct

from threedllm.exporters.base import Exporter3D
from threedllm.generators.base import MeshResult


class STLExporter(Exporter3D):
    """Exports meshes in binary STL format."""

    def get_file_extension(self) -> str:
        """Get the file extension."""
        return ".stl"

    def _compute_normal(self, v0, v1, v2):
        """Compute face normal from three vertices."""
        # Compute cross product: (v1 - v0) × (v2 - v0)
        dx1 = v1[0] - v0[0]
        dy1 = v1[1] - v0[1]
        dz1 = v1[2] - v0[2]
        dx2 = v2[0] - v0[0]
        dy2 = v2[1] - v0[1]
        dz2 = v2[2] - v0[2]

        # Cross product
        nx = dy1 * dz2 - dz1 * dy2
        ny = dz1 * dx2 - dx1 * dz2
        nz = dx1 * dy2 - dy1 * dx2

        # Normalize
        norm = (nx * nx + ny * ny + nz * nz) ** 0.5
        if norm > 0:
            return (nx / norm, ny / norm, nz / norm)
        return (0.0, 0.0, 1.0)  # Default normal if degenerate

    def export(self, result: MeshResult, path: str) -> None:
        """Export mesh as binary STL file."""
        if not result.faces:
            raise ValueError("STL export requires faces. Use OBJ or PLY for point clouds.")

        with open(path, "wb") as f:
            # Write 80-byte header
            header = b"STL file generated by ThreeDLLM"
            if result.prompt:
                header = result.prompt[:80].encode("utf-8")
            f.write(header.ljust(80, b"\x00"))

            # Write number of faces (4 bytes, little-endian)
            num_faces = len(result.faces)
            f.write(struct.pack("<I", num_faces))

            # Write each face
            for face in result.faces:
                v0 = result.vertices[face[0]]
                v1 = result.vertices[face[1]]
                v2 = result.vertices[face[2]]

                # Compute normal
                normal = self._compute_normal(v0, v1, v2)

                # Write normal (3 floats)
                f.write(struct.pack("<fff", *normal))

                # Write vertices (3 floats each)
                f.write(struct.pack("<fff", *v0))
                f.write(struct.pack("<fff", *v1))
                f.write(struct.pack("<fff", *v2))

                # Write attribute byte count (2 bytes, usually 0)
                f.write(struct.pack("<H", 0))
